### ISSUE TITLE
Datanode: lastpacketinblock parity

### ISSUE THREAD

**Issue by cemeyer** [alexsmith1612/hadoofus#50]
Reported by Alex Smith.

The Java and libhdfs3 clients send an empty final packet at the end of a block, with the lastpacketinblock flag set.  They do not send a data packet with the flag set.  For parity / reduction of risk, we should do the same thing.  This may also make it easier to trickle data in (needs further API enhancement outside of the scope of this issue, though).

**Comment by alexsmith1612** [comment]
Fixed by PR #67
